spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2-liq
    username: star
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true