spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:cloudspanner:/projects/ajoara-dev/instances/ajoara-dev-instance/databases/ajoara
  jpa:
    database-platform: com.google.cloud.spanner.hibernate.SpannerDialect
    hibernate:
      ddl-auto: none
